### ISSUE TITLE
An error when loading ctb.bilstm.joint4.model

### ISSUE THREAD

**Issue by CP-here** [jiesutd/RichWordSegmentor#1]
I can succesfully run your demo.sh
but when I want to use ctb.bilstm.joint4.model to run test.data as
`./STDSeg -test test.data -model ctb.bilstm.joint4.model -output 1.txt`
 an error goes like that:
`Start load model from file: ctb.bilstm.joint4.model
[17:19:23] /mnt/c/Users/13504/Documents/github/RichWordSegmentor-master/../mshadow-master/mshadow/././././extension/../packet-inl.h:72: Check failed: (ret) == (0) AlignedMallocPitch failed
Aborted (core dumped)`

**Comment by CP-here** [comment]
and I'm using this version of mshadow
https://github.com/dmlc/mshadow/tree/master/mshadow

**Comment by jiesutd** [comment]
Hi @HHUSaltedFish , that's strange. Are you sure if you download the model successfully?  Normally it will not give errors if the model file is correct.

**Comment by CP-here** [comment]
emmmm
I download it again and still have the same question.

**Comment by jiesutd** [comment]
I am not sure if it is caused by the update of mshadow.  Could you please give me an email and I will send you the mshadow I used?

**Comment by yuyingzz** [comment]
Hi @jiesutd @CP-here  
I met the same problem recently.
 Is that caused by the update of mshadow?

**Comment by jiesutd** [comment]
> Hi @jiesutd @CP-here
> I met the same problem recently.
> Is that caused by the update of mshadow?

Yes, it is caused by the update of mshadow. Use the old version will solve the problem.
